export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";
export const FETCHING_DATA_MID = "FETCHING_DATA_MID";
export const INDEX_SELECT = "INDEX_SELECT";
export const FETCHING_DATA_ALL = "FETCHING_DATA_ALL";
export const FETCHING_DATA_HOME = "FETCHING_DATA_HOME";
export const USER_ADD_COLOR = "USER_ADD_COLOR";